### PR TITLE
Add py35 support to lang/py

### PR DESCRIPTION
**Pull request by ipwnponies**

### CODE REVIEW

**Review by ipwnponies — COMMENTED** [review]
I'm not sure if this is how the versioning of this package should be handled. I've updated the version in setup.py from templated value and changed the package name. This was required to make this branch usable as editable installation with pip.

**Comment by abrarsheikh** [comment]
this looks good to me

**Comment by justincinmd** [comment]
@abrarsheikh could you give this another look, and merge it if you think it's OK?

**Comment by premsantosh** [comment]
The change looks fine but I had one question. There is already a py3 folder under lang. Are we just ignoring that for now?

**Pull request merged**
